### ISSUE TITLE
Update upload auth using new secrets

### ISSUE THREAD

**Issue by kammce** [libhal-google/libhal-micromod#13]
Signing into JFROG should look like this:

```yaml
      - name: 📡 Sign into JFrog Artifactory
        env:
          PASSWORD: ${{ secrets.JFROG_LIBHAL_TRUNK_ID_TOKEN }}
          JFROG_USER: ${{ secrets.JFROG_LIBHAL_TRUNK_ID_TOKEN_USER }}
        run: conan remote login -p $PASSWORD libhal $JFROG_USER
```

Not 

```yaml
      - name: 📡 Sign into JFrog Artifactory
        if: ${{ github.ref == 'refs/heads/main' && runner.os != 'Windows' }}
        env:
          API_KEY: ${{ secrets.JFROG_LIBHAL_TRUNK_API_KEY }}
          JFROG_USER: ${{ secrets.JFROG_LIBHAL_TRUNK_USER }}
        run: conan remote login -p $API_KEY libhal-trunk $JFROG_USER
```
